version: "3.9"

services:
  db:
    image: postgres
    container_name: db_prisma_deliveries
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma_deliveries
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    networks:
      - prisma_deliveries

  app:
    build: .
    container_name: prisma_deliveries
    volumes:
      - .:/usr/app
    depends_on:
      - db_prisma_deliveries
    networks:
      - prisma_deliveries

volumes:
  postgres:
    driver: local

networks:
  prisma_deliveries:
    driver: bridge
